/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Interfaces.Cartelera;

/**
 *
 * @author INES CHAR
 */
public class VentaCine extends javax.swing.JFrame {

    private static VentaCine ventacine;
    
    /**
     * Creates new form VentaCine
     */
    public VentaCine() {
        initComponents();
    }

    //implementar singleton
    public static VentaCine getVentaCine(){
        if(ventacine==null){
            ventacine = new VentaCine();
        }
        return ventacine;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        peliculas = new javax.swing.JComboBox<>();
        cantidadPersonas = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        duracion = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        botonCambiar = new javax.swing.JButton();
        botonCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        peliculas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "El gato con botas", "Creed", "Quantumania", "Scream 6" }));
        peliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peliculasActionPerformed(evt);
            }
        });
        jPanel1.add(peliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 150, 20));
        jPanel1.add(cantidadPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 150, -1));

        precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioActionPerformed(evt);
            }
        });
        jPanel1.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 150, -1));
        jPanel1.add(duracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 150, -1));

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 150, -1));

        botonCambiar.setText("CAMBIAR");
        botonCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarActionPerformed(evt);
            }
        });
        jPanel1.add(botonCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 90, 30));

        botonCalcular.setText("CALCULAR");
        botonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(botonCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioActionPerformed

    private void peliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peliculasActionPerformed
        // TODO add your handling code here:
        
        String valorPrecio = "";
        String duracionPelicula = "";
        
        switch (peliculas.getSelectedIndex()){
            
            case 0:
                
                valorPrecio = "$ 7.000";
                precio.setText(valorPrecio);
                duracionPelicula = "124 minutos";
                duracion.setText(duracionPelicula);
                
            case 1:
                
                valorPrecio = "$ 5.000";
                precio.setText(valorPrecio);
                duracionPelicula = "148 minutos";
                duracion.setText(duracionPelicula);
                
            case 2: 
                
                valorPrecio = "$ 6.000";
                precio.setText(valorPrecio);
                duracionPelicula = "115 minutos";
                duracion.setText(duracionPelicula);
                
            case 3:
                
                valorPrecio = "$ 8.000";
                precio.setText(valorPrecio);
                duracionPelicula = "193 minutos";
                duracion.setText(duracionPelicula);
                
        }
    }//GEN-LAST:event_peliculasActionPerformed

    private void botonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularActionPerformed
        // TODO add your handling code here:
        
        int cantidadPelicula;
        int valorPrecio;
        int descuentoPelicula;
        String totalVenta;
        
        cantidadPelicula = Integer.parseInt(cantidadPersonas.getText());
        valorPrecio = Integer.parseInt(precio.getText());
        
        totalVenta = Integer.toString(cantidadPelicula * valorPrecio);

        total.setText(totalVenta);
  
    }//GEN-LAST:event_botonCalcularActionPerformed

    private void botonCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarActionPerformed
        // TODO add your handling code here:
        
        precio.setText(null);
        duracion.setText(null);
        cantidadPersonas.setText(null);
        total.setText(null);
        
    }//GEN-LAST:event_botonCambiarActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        String totalVenta = null;
        // TODO add your handling code here:
        
        total.setText(totalVenta);
        
    }//GEN-LAST:event_totalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentaCine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalcular;
    private javax.swing.JButton botonCambiar;
    private javax.swing.JTextField cantidadPersonas;
    private javax.swing.JTextField duracion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> peliculas;
    private javax.swing.JTextField precio;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
