/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Interfaces.Cartelera;

/**
 *
 * @author INES CHAR
 */
public class VentaCine extends javax.swing.JFrame {

    private static VentaCine ventacine;
    
    /**
     * Creates new form VentaCine
     */
    public VentaCine() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    //implementar singleton
    public static VentaCine getVentaCine(){
        if(ventacine==null){
            ventacine = new VentaCine();
        }
        return ventacine;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        total = new javax.swing.JTextField();
        botonCalcular = new javax.swing.JButton();
        botonCambiar = new javax.swing.JButton();
        peliculas = new javax.swing.JComboBox<>();
        precio = new javax.swing.JTextField();
        duracion = new javax.swing.JTextField();
        cantidadPersonas = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonCalcular1 = new javax.swing.JButton();
        botonCalcular2 = new javax.swing.JButton();
        botonCalcular3 = new javax.swing.JButton();
        botonCalcular4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel2.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 150, -1));

        botonCalcular.setBackground(new java.awt.Color(204, 0, 0));
        botonCalcular.setForeground(new java.awt.Color(255, 255, 255));
        botonCalcular.setText("CALCULAR");
        botonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularActionPerformed(evt);
            }
        });
        jPanel2.add(botonCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 120, 30));

        botonCambiar.setBackground(new java.awt.Color(204, 0, 0));
        botonCambiar.setForeground(new java.awt.Color(255, 255, 255));
        botonCambiar.setText("CAMBIAR");
        botonCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarActionPerformed(evt);
            }
        });
        jPanel2.add(botonCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 90, 30));

        peliculas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "El gato con botas", "Creed", "Quantumania", "Scream 6" }));
        peliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peliculasActionPerformed(evt);
            }
        });
        jPanel2.add(peliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 150, 20));

        precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioActionPerformed(evt);
            }
        });
        jPanel2.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 150, -1));
        jPanel2.add(duracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 150, -1));
        jPanel2.add(cantidadPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 150, -1));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("PELICULA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 560, -1));

        jButton3.setBackground(new java.awt.Color(204, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("PELICULA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 560, -1));

        jButton4.setBackground(new java.awt.Color(204, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("PELICULA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 560, -1));

        jButton5.setBackground(new java.awt.Color(204, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("PELICULA");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 560, -1));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        botonCalcular1.setBackground(new java.awt.Color(204, 0, 0));
        botonCalcular1.setForeground(new java.awt.Color(255, 255, 255));
        botonCalcular1.setText("CANTIDAD DE PERSONAS");
        botonCalcular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcular1ActionPerformed(evt);
            }
        });
        jPanel2.add(botonCalcular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 170, 30));

        botonCalcular2.setBackground(new java.awt.Color(204, 0, 0));
        botonCalcular2.setForeground(new java.awt.Color(255, 255, 255));
        botonCalcular2.setText("PELICULA");
        botonCalcular2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcular2ActionPerformed(evt);
            }
        });
        jPanel2.add(botonCalcular2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 120, 30));

        botonCalcular3.setBackground(new java.awt.Color(204, 0, 0));
        botonCalcular3.setForeground(new java.awt.Color(255, 255, 255));
        botonCalcular3.setText("PRECIO");
        botonCalcular3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcular3ActionPerformed(evt);
            }
        });
        jPanel2.add(botonCalcular3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 120, 30));

        botonCalcular4.setBackground(new java.awt.Color(204, 0, 0));
        botonCalcular4.setForeground(new java.awt.Color(255, 255, 255));
        botonCalcular4.setText("DURACIÓN");
        botonCalcular4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcular4ActionPerformed(evt);
            }
        });
        jPanel2.add(botonCalcular4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 120, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Cinemark - Producción de Video Comercial Tarjeta Elite Gold (1).gif"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 660, 340));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 360));

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("FACTURAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 700, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioActionPerformed

    private void peliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peliculasActionPerformed
        // TODO add your handling code here:
        
        String valorPrecio = "";
        String duracionPelicula = "";
        
        switch (peliculas.getSelectedIndex()){
            
            case 0:
                
                valorPrecio = "$ 7.000";
                precio.setText(valorPrecio);
                duracionPelicula = "124 minutos";
                duracion.setText(duracionPelicula);
                
            case 1:
                
                valorPrecio = "$ 5.000";
                precio.setText(valorPrecio);
                duracionPelicula = "148 minutos";
                duracion.setText(duracionPelicula);
                
            case 2: 
                
                valorPrecio = "$ 6.000";
                precio.setText(valorPrecio);
                duracionPelicula = "115 minutos";
                duracion.setText(duracionPelicula);
                
            case 3:
                
                valorPrecio = "$ 8.000";
                precio.setText(valorPrecio);
                duracionPelicula = "193 minutos";
                duracion.setText(duracionPelicula);
                
        }
    }//GEN-LAST:event_peliculasActionPerformed

    private void botonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularActionPerformed
        // TODO add your handling code here:
        
        String cantidadPelicula;
        String valorPrecio;
        String totalVenta;
        
        cantidadPelicula = (cantidadPersonas.getText());
        valorPrecio = (precio.getText());
        
        totalVenta = (cantidadPelicula * valorPrecio);

        total.setText(totalVenta);
  
    }//GEN-LAST:event_botonCalcularActionPerformed

    private void botonCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarActionPerformed
        // TODO add your handling code here:
        
        precio.setText(null);
        duracion.setText(null);
        cantidadPersonas.setText(null);
        total.setText(null);
        
    }//GEN-LAST:event_botonCambiarActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        String totalVenta = null;
        // TODO add your handling code here:
        
        total.setText(totalVenta);
        
    }//GEN-LAST:event_totalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //MUESTRA LA SIGUIENTE PANTALLA
        Login.getLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void botonCalcular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcular1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCalcular1ActionPerformed

    private void botonCalcular2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcular2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCalcular2ActionPerformed

    private void botonCalcular3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcular3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCalcular3ActionPerformed

    private void botonCalcular4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcular4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCalcular4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentaCine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalcular;
    private javax.swing.JButton botonCalcular1;
    private javax.swing.JButton botonCalcular2;
    private javax.swing.JButton botonCalcular3;
    private javax.swing.JButton botonCalcular4;
    private javax.swing.JButton botonCambiar;
    private javax.swing.JTextField cantidadPersonas;
    private javax.swing.JTextField duracion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> peliculas;
    private javax.swing.JTextField precio;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
